### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lgtk** [dmaevsky/ellx_examples#1]
![image](https://user-images.githubusercontent.com/67309823/85372466-d9006a80-b56c-11ea-8fdb-e55de2e0f6ab.png)

**Comment by dmaevsky** [comment]
Thank you very much for reporting this issue !
We have just launched a semi-private alpha last Sunday, and some things might have been broken.
This particular project was an old one, and was missing some fields in the database.
I removed it for now.
We are currently rolling out new and more and more interesting examples every day. Please, check out [this one](https://ellx.io/matyunya/10print) for instance, made by my colleague.

A standard library of tools and components is coming soon too.

We would warmly welcome all and any feedback !
 How did you stumble upon our site at the first place ? :)

Hope to count you soon among our users !

Kind regards,
Dmitry
